services:
  web:
    build: .
    container_name: django_app
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/text_to_handwritting
      - ./media:/text_to_handwritting/media
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    container_name: celery_worker
    command: ["celery", "-A", "text_to_handwritting", "worker", "--loglevel=info"]
    depends_on:
      - redis
    volumes:
      - .:/text_to_handwritting
      - /var/run/docker.sock:/var/run/docker.sock  # Allow Docker access
