name: Django CI/CD with Docker, Celery, Redis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Django Tests in Docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install docker-compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Build services
        run: docker-compose -f docker-compose.yml build

      - name: Start services
        run: docker-compose -f docker-compose.yml up -d

      - name: Wait for services to be healthy
        run: sleep 10

      - name: Tear down services
        if: always()
        run: docker-compose down

  deploy:
    name: Deploy to Production Server
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.CLOUD_HOST }}
          username: ${{ secrets.CLOUD_USER }}
          port: 22
          script: |
            cd /home/ubuntu/Text-to-handwriting
            git pull origin main
            docker-compose down
            docker-compose up --build -d
